FROM php:7-fpm

LABEL Description="This image provides PHP-fpm with common extensions"
MAINTAINER Grgiori Kochanov public@grik.net


# variables $PHP_INI_DIR, $PHP_VERSION, $PHP_FILENAME are defined in the parent Dockerfile
ENV XDEBUG_FILENAME xdebug-2.4.0rc4.tgz

# php source code path is hardcoded in the parent Dockerfile
ENV PHP_SOURCE_PATH /usr/src/php


RUN php_extensions_setup.sh


# Generate an extended CLI version

RUN cd /usr/src/php \
    && apt-get update && apt-get install -y --no-install-recommends libcurl4-openssl-dev libreadline6-dev \
    && ./configure \
    --with-config-file-path="$PHP_INI_DIR" \
    --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
    --with-fpm-user=www-data --with-fpm-group=www-data \
    --disable-cgi --enable-ftp --with-zlib --enable-mysqlnd --with-readline --with-openssl --with-curl \
    --enable-sockets --enable-sysvsem --enable-sysvshm --enable-shmop --enable-posix --without-pear --enable-pcntl
    && make -j"$(nproc)" && make install && make clean
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false \
        libcurl4-openssl-dev libreadline6-dev
