version: "3.8"

services:
  application:
    command: ["-F","-c", "/usr/local/etc/php/php.ini-development"]
    environment:
      - XDEBUG_MODE=debug
    build:
      context: docker
      dockerfile: baseline-image.Dockerfile
