version: "3.8"

services:

  router:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - fpm-socket:/fpm-socket/

  application:
    image: grigori/demo-application
    build:
      context: docker
      dockerfile: production-build.Dockerfile
    expose:
      - 9000
    volumes:
      # application code
      - fpm-socket:/fpm-socket/
      - type: bind
        source: ./src/
        target: /opt/www
      - type: bind
        source: ./etc/
        target: /usr/local/etc/
      - type: bind
        source: ./docker-entrypoint-init.d/
        target: /docker-entrypoint-init.d/
    command: ["-F","-c", "/usr/local/etc/php/php.ini-production"]

volumes:
  fpm-socket:

