memcached:
  image: tenstartups/memcached
  container_name: memcached

nginx:
  image: nginx
  container_name: nginx
  volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
      - ./wwwroot:/opt/www
  ports:
   - "8080:80"
  links:
   - php-fpm
   - memcached

php-fpm:
  image: grigori/phpextensions
  container_name: php-fpm
  command: [php-fpm]
  volumes:
    - ./etc/:/usr/local/etc/
    - ./logs:/var/log/php/
    - ./upload_tmp:/var/upload_tmp/
    - ./:/opt/www/
  links:
    - memcached
    - mysql

mysql:
  image: mariadb
  container_name: mysql
  environment:
    -  MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./etc/my.custom.cnf:/etc/mysql/conf.d/my.custom.cnf
    - ./logs/mysqld.log:/var/log/mysqld.log