#!/bin/sh

test "$(ls /usr/local/etc/php* 2>/dev/null)" || cp -R /usr/src/etc /usr/local/

set -e


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
